spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/todo_list?characterEncoding=utf-8&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

    # dbcp2 数据源
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-idle: 10
      max-total: 50
      max-wait-millis: 10000
      initial-size: 6

  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML5
    suffix: .html

mybatis:
  mapper-locations: /mappers/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging.level.org.springframework.boot.autoconfigure: ERROR

