export const TODOLIST_REQUEST = 'TODOLIST_REQUEST'
export const TODOLIST_SUCCESS = 'TODOLIST_SUCCESS'
export const TODOLIST_FAILURE = 'TODOLIST_FAILURE'
export const TODOLIST_ADD = 'TODOLIST_ADD'
export const TODOLIST_DELETE = 'TODOLIST_DELETE'

export const HEADER_TEXT_CHANGE = 'HEADER_TEXT_CHANGE'